In [1]:
import pandas as pd
import glob

Consolidating Fundamentals

In [ ]:
symbols = ['GOOGL', 'META', 'MSFT', 'NVDA', 'PLTR']

In [13]:
all_files = []
for symbol in symbols:

    csv_files = glob.glob(f'/workspaces/bubbleindex/bronze/{symbol}/*.csv')
    all_files.append(csv_files)

In [14]:
print(all_files)

[['/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv'], ['/workspaces/bubbleindex/bronze/META/META_price.csv', '/workspaces/bubbleindex/bronze/META/META_balancesheet.csv', '/workspaces/bubbleindex/bronze/META/META_incomestatement.csv', '/workspaces/bubbleindex/bronze/META/META_cashflow.csv'], ['/workspaces/bubbleindex/bronze/MSFT/MSFT_price.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_cashflow.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_incomestatement.csv'], ['/workspaces/bubbleindex/bronze/NVDA/NVDA_price.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_cashflow.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_balancesheet.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_incomestatement.csv'], ['/workspaces/bubbleindex/bronze/PLTR/PLTR_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_incomestatement.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_price.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_balancesheet.csv']]

In [21]:

#list of fundamentals for each company (googldf, metadf, pltrdf2,etc)
final_fundamentals_dfs = []
#symbol = ['/workspaces/bubbleindex/bronze/GOOGL/GOOGL_price.csv', 
#           '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', 
#       # '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', 
#       '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv']
for symbol in all_files:
    #list of all fundamentals dfs (df,df1,df2)
    fundamentals_files = []

    #csvfile = '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv
    for csv_file in symbol:
        #if csv_file is a price file skip it
        if not csv_file.endswith('_price.csv'):
            df = pd.read_csv(csv_file)
            df = df.rename(columns={'Unnamed: 0': 'Date'}) 

            #filter columns based on file type
            if csv_file.endswith('_balancesheet.csv'):
                df = df[['ticker', 'Date', 'Total Debt', 'Working Capital']]
            elif csv_file.endswith('_cashflow.csv'):
                df = df[['ticker', 'Date', 'Free Cash Flow', 'Beginning Cash Position' , 'End Cash Position']]
            else:
                df = df[['ticker', 'Date', 'Total Revenue', 'Gross Profit', 'Net Income', 'Diluted EPS', 'Research And Development', 'EBITDA', 'Tax Provision']]
            fundamentals_files.append(df)
    
    fundamentals_df = fundamentals_files[0].merge(fundamentals_files[1], on=['ticker', 'Date'], how='inner').merge(fundamentals_files[2], on=['ticker', 'Date'], how='inner')
    #fundamentals_df.to_csv(f'/workspaces/bubbleindex/silver/fundamentals.csv', index=False)
    final_fundamentals_dfs.append(fundamentals_df)


# combine all fundamentals dfs into one
combined_fundamentals = pd.concat([final_fundamentals_dfs[0], final_fundamentals_dfs[1], final_fundamentals_dfs[2], final_fundamentals_dfs[3], final_fundamentals_dfs[4]],  ignore_index=True)
combined_fundamentals.to_csv('/workspaces/bubbleindex/silver/combined_fundamentals.csv', index=False)

In [ ]:

# drop all “price” csvs from the list
csv_files = [f for f in csv_files if not f.endswith('_price.csv')]
print(csv_files)

['/workspaces/bubbleindex/bronze/META/META_balancesheet.csv', '/workspaces/bubbleindex/bronze/META/META_incomestatement.csv', '/workspaces/bubbleindex/bronze/META/META_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_cashflow.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_incomestatement.csv', '/workspaces/bubbleindex/bronze/PLTR/PLTR_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_balancesheet.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_cashflow.csv', '/workspaces/bubbleindex/bronze/MSFT/MSFT_incomestatement.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_cashflow.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_balancesheet.csv', '/workspaces/bubbleindex/bronze/NVDA/NVDA_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_incomestatement.csv', '/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv']

GOOGL fundamentals

In [20]:
df = pd.read_csv(r'/workspaces/bubbleindex/bronze/GOOGL/GOOGL_balancesheet.csv')

In [21]:
df

,Unnamed: 0,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,...,Inventory,Receivables,Taxes Receivable,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,ticker
0,2025-12-31,NaN,1.208800e+10,1.208800e+10,1.583900e+10,5.929100e+10,3.818850e+11,4.618120e+11,1.032930e+11,3.818850e+11,...,NaN,6.288600e+10,NaN,6.288600e+10,-924000000.0,6.381000e+10,1.268430e+11,9.613500e+10,3.070800e+10,GOOGL
1,2024-12-31,NaN,1.221100e+10,1.221100e+10,NaN,2.257400e+10,2.931990e+11,3.359670e+11,7.458900e+10,2.931990e+11,...,NaN,5.234000e+10,NaN,5.234000e+10,-879000000.0,5.321900e+10,9.565700e+10,7.219100e+10,2.346600e+10,GOOGL
2,2023-12-31,0.0,1.246000e+10,1.246000e+10,NaN,2.712100e+10,2.541810e+11,2.952490e+11,8.971600e+10,2.541810e+11,...,NaN,4.796400e+10,NaN,4.796400e+10,-771000000.0,4.873500e+10,1.109160e+11,8.686800e+10,2.404800e+10,GOOGL
3,2022-12-31,NaN,1.284900e+10,1.284900e+10,NaN,2.967900e+10,2.271840e+11,2.690010e+11,9.549500e+10,2.271840e+11,...,2.670000e+09,4.025800e+10,NaN,4.025800e+10,-754000000.0,4.101200e+10,1.137620e+11,9.188300e+10,2.187900e+10,GOOGL
4,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.170000e+09,NaN,966000000.0,NaN,NaN,NaN,NaN,NaN,NaN,GOOGL

In [22]:
df = df.rename(columns={'Unnamed: 0': 'Date'})

In [23]:
df = df[['ticker', 'Date', 'Total Debt', 'Working Capital']]

In [24]:
df

  ticker        Date    Total Debt  Working Capital
0  GOOGL  2025-12-31  5.929100e+10     1.032930e+11
1  GOOGL  2024-12-31  2.257400e+10     7.458900e+10
2  GOOGL  2023-12-31  2.712100e+10     8.971600e+10
3  GOOGL  2022-12-31  2.967900e+10     9.549500e+10
4  GOOGL  2021-12-31           NaN              NaN

In [25]:
df.columns

Index(['ticker', 'Date', 'Total Debt', 'Working Capital'], dtype='str')

In [26]:
df1 = pd.read_csv(r'/workspaces/bubbleindex/bronze/GOOGL/GOOGL_cashflow.csv')

In [27]:
df1 = df1.rename(columns={'Unnamed: 0': 'Date'})