In [4]:
import pandas as pd
import numpy as np

<h2>Valuation Analysis</h2>
identifyng overvalued stocks by comparing:
<ul><strong>Valuation:</strong>P/E ratio, Price-to-Sales</ul>
<ul><strong>Growth:</strong>Revenue growth rate</ul>
<ul><strong>Profitability:</strong>Net profit Margin</ul>
<ul><strong>Risk</strong>Bubble risk score(0-100)</ul>

In [5]:
fundamentals = pd.read_csv('/workspaces/bubbleindex/silver/combined_fundamentals.csv')
prices = pd.read_csv('/workspaces/bubbleindex/silver/combined_stockprices.csv')

In [6]:
fundamentals['Date'] = pd.to_datetime(fundamentals['Date'])
prices['Date'] = pd.to_datetime(prices['Date'], utc='True')

Fundamentals Analysis

In [7]:
#get latest fundamentals & prices for each company
latest_fundamentals = fundamentals.sort_values('Date').groupby('ticker').tail(1).reset_index(drop=True)
latest_prices = prices.sort_values('Date').groupby('ticker').tail(1).reset_index(drop=True)

In [8]:
latest_fundamentals.head()

,ticker,Date,Free Cash Flow,Beginning Cash Position,End Cash Position,Total Revenue,Gross Profit,Net Income,Diluted EPS,Research And Development,...,Gross Margin,Net Margin,FCF Margin,Debt to Equity,Working Capital Ratio,R&D to Revenue,Revenue growth,Net Income Growth,EPS Growth,FCF Growth
0,MSFT,2025-06-30,7.161100e+10,1.831500e+10,3.024200e+10,2.817240e+11,1.938930e+11,1.018320e+11,13.64,3.248800e+10,...,0.688237,0.361460,0.254188,0.548303,0.177170,0.115319,0.149322,0.155396,0.155932,-0.033211
1,META,2025-12-31,4.610900e+10,4.543800e+10,3.910000e+10,2.009660e+11,1.647910e+11,6.045800e+10,NaN,5.737200e+10,...,0.819994,0.300837,0.229437,0.556409,0.332822,0.285481,0.221670,-0.030500,NaN,-0.147267
2,GOOGL,2025-12-31,7.326600e+10,2.346600e+10,3.070800e+10,4.028360e+11,2.403010e+11,1.321700e+11,10.81,6.108700e+10,...,0.596523,0.328099,0.181876,0.364679,0.256415,0.151642,0.150901,0.320142,0.344527,0.006899
3,PLTR,2025-12-31,2.100591e+09,2.119936e+09,1.451425e+09,4.475446e+09,3.686269e+09,1.625033e+09,0.63,5.576770e+08,...,0.823665,0.363100,0.469359,0.030942,1.604889,0.124608,0.561834,2.515941,2.310962,0.840636
4,NVDA,2026-01-31,9.667600e+10,8.589000e+09,1.060500e+10,2.159380e+11,1.534630e+11,1.200670e+11,4.90,1.849700e+10,...,0.710681,0.556025,0.447703,0.105664,0.432726,0.085659,0.654735,0.647462,0.666667,0.588681

In [18]:
fund_trends = fundamentals.sort_values(['ticker', 'Date']).copy()

In [19]:
fund_trends

,ticker,Date,Free Cash Flow,Beginning Cash Position,End Cash Position,Total Revenue,Gross Profit,Net Income,Diluted EPS,Research And Development,...,Gross Margin,Net Margin,FCF Margin,Debt to Equity,Working Capital Ratio,R&D to Revenue,Revenue growth,Net Income Growth,EPS Growth,FCF Growth
0,GOOGL,2022-12-31,6.001000e+10,2.094500e+10,2.187900e+10,2.828360e+11,1.566330e+11,5.997200e+10,4.560000,3.950000e+10,...,0.553794,0.212038,0.212172,0.237102,0.337634,0.139657,NaN,NaN,NaN,NaN
1,GOOGL,2023-12-31,6.949500e+10,2.187900e+10,2.404800e+10,3.073940e+11,1.740620e+11,7.379500e+10,5.800000,4.542700e+10,...,0.566250,0.240066,0.226078,0.232127,0.291860,0.147781,0.086828,0.230491,0.271930,0.158057
2,GOOGL,2024-12-31,7.276400e+10,2.404800e+10,2.346600e+10,3.500180e+11,2.037120e+11,1.001180e+11,8.040000,4.932600e+10,...,0.582004,0.286037,0.207886,0.232331,0.213100,0.140924,0.138662,0.356704,0.386207,0.047039
3,GOOGL,2025-12-31,7.326600e+10,2.346600e+10,3.070800e+10,4.028360e+11,2.403010e+11,1.321700e+11,10.810000,6.108700e+10,...,0.596523,0.328099,0.181876,0.364679,0.256415,0.151642,0.150901,0.320142,0.344527,0.006899
4,META,2022-12-31,1.928900e+10,1.686500e+10,1.559600e+10,1.166090e+11,9.136000e+10,2.320000e+10,8.590000,3.533800e+10,...,0.783473,0.198955,0.165416,0.449826,0.278906,0.303047,NaN,NaN,NaN,NaN
5,META,2023-12-31,4.406800e+10,1.559600e+10,4.282700e+10,1.349020e+11,1.089430e+11,3.909800e+10,14.870000,3.848300e+10,...,0.807571,0.289825,0.326667,0.410794,0.395880,0.285266,0.156875,0.685259,0.731083,1.284618
6,META,2024-12-31,5.407200e+10,4.282700e+10,4.543800e+10,1.645010e+11,1.343400e+11,6.236000e+10,23.860000,4.387300e+10,...,0.816652,0.379086,0.328703,0.424729,0.403943,0.266704,0.219411,0.594966,0.604573,0.227013
7,META,2025-12-31,4.610900e+10,4.543800e+10,3.910000e+10,2.009660e+11,1.647910e+11,6.045800e+10,NaN,5.737200e+10,...,0.819994,0.300837,0.229437,0.556409,0.332822,0.285481,0.221670,-0.030500,NaN,-0.147267
8,MSFT,2022-06-30,6.514900e+10,1.422400e+10,1.393100e+10,1.982700e+11,1.356200e+11,7.273800e+10,9.650000,2.451200e+10,...,0.684017,0.366863,0.328587,0.450939,0.376265,0.123629,NaN,NaN,NaN,NaN
9,MSFT,2023-06-30,5.947500e+10,1.393100e+10,3.470400e+10,2.119150e+11,1.460520e+11,7.236100e+10,9.680000,2.719500e+10,...,0.689201,0.341462,0.280655,0.428098,0.378019,0.128330,0.068820,-0.005183,0.003109,-0.087093
10,MSFT,2024-06-30,7.407100e+10,3.470400e+10,1.831500e+10,2.451220e+11,1.710080e+11,8.813600e+10,11.800000,2.951000e+10,...,0.697644,0.359560,0.302180,0.660861,0.140534,0.120389,0.156700,0.218004,0.219008,0.245414
11,MSFT,2025-06-30,7.161100e+10,1.831500e+10,3.024200e+10,2.817240e+11,1.938930e+11,1.018320e+11,13.640000,3.248800e+10,...,0.688237,0.361460,0.254188,0.548303,0.177170,0.115319,0.149322,0.155396,0.155932,-0.033211
12,NVDA,2023-01-31,3.808000e+09,1.990000e+09,3.389000e+09,2.697400e+10,1.535600e+10,4.368000e+09,0.174000,7.339000e+09,...,0.569289,0.161934,0.141173,0.421534,0.612071,0.272077,NaN,NaN,NaN,NaN
13,NVDA,2024-01-31,2.702100e+10,3.389000e+09,7.280000e+09,6.092200e+10,4.430100e+10,2.976000e+10,1.190000,8.675000e+09,...,0.727176,0.488493,0.443534,0.246951,0.553396,0.142395,1.258545,5.813187,5.839080,6.095851
14,NVDA,2025-01-31,6.085300e+10,7.280000e+09,8.589000e+09,1.304970e+11,9.785800e+10,7.288000e+10,2.940000,1.291400e+10,...,0.749887,0.558480,0.466317,0.138522,0.475712,0.098960,1.142034,1.448925,1.470588,1.252063
15,NVDA,2026-01-31,9.667600e+10,8.589000e+09,1.060500e+10,2.159380e+11,1.534630e+11,1.200670e+11,4.900000,1.849700e+10,...,0.710681,0.556025,0.447703,0.105664,0.432726,0.085659,0.654735,0.647462,0.666667,0.588681
16,PLTR,2022-12-31,1.837100e+08,2.366914e+09,2.627335e+09,1.905871e+09,1.497322e+09,-3.737050e+08,-0.180263,3.596790e+08,...,0.785637,-0.196081,0.096392,0.092268,1.287409,0.188722,NaN,NaN,NaN,NaN
17,PLTR,2023-12-31,6.970690e+08,2.627335e+09,8.501070e+08,2.225012e+09,1.793907e+09,2.098250e+08,0.090131,4.046240e+08,...,0.806246,0.094303,0.313288,0.063333,1.524756,0.181853,0.167452,-1.561472,-1.499997,2.794399
18,PLTR,2024-12-31,1.141231e+09,8.501070e+08,2.119936e+09,2.865507e+09,2.299517e+09,4.621900e+08,0.190277,5.078780e+08,...,0.802482,0.161294,0.398265,0.046204,1.723350,0.177238,0.287861,1.202740,1.111116,0.637185
19,PLTR,2025-12-31,2.100591e+09,2.119936e+09,1.451425e+09,4.475446e+09,3.686269e+09,1.625033e+09,0.630000,5.576770e+08,...,0.823665,0.363100,0.469359,0.030942,1.604889,0.124608,0.561834,2.515941,2.310962,0.840636

In [20]:
print(sorted(fund_trends['ticker'].unique()))

['GOOGL', 'META', 'MSFT', 'NVDA', 'PLTR']

Profitability trend of each company (Net Margin %)

percentage change for each company 

eg. google[ending net margin] -  [start net margin]
for a metric measurement or like comparions u would prefer to
see the relative change then just numbers

In [12]:
print('Net Margin:\n')
for ticker in sorted(fund_trends['ticker'].unique()):
    ticker_data = fund_trends[fund_trends['ticker'] == ticker]
    ticker_data = ticker_data[['Date', 'Net Margin']].copy()
    ticker_data['Net Margin'] = ticker_data['Net Margin'] * 100
    ticker_data = ticker_data.sort_values('Date')
    
    #if ticker_data has more than 1 entry then calculate the change in net margin from the first to the last entry 
    if len(ticker_data) > 1:
        margin_change = ticker_data['Net Margin'].iloc[-1]  - ticker_data['Net Margin'].iloc[0]
        print(f"{ticker} Net Margin Change: {ticker_data['Net Margin'].iloc[-1]:.1f}% Current Margin | {margin_change:.1f}% change")
    else:
        print(f'{ticker} Net Margin: {ticker_data["Net Margin"].values[0]:.1f}% (limited data)')

print("\nRevenue Growth Trends:\n")
for ticker in sorted(fund_trends['ticker'].unique()):
    ticker_data = fund_trends[fund_trends['ticker'] == ticker]
    ticker_data = ticker_data[['Date', 'Revenue growth']].copy()
    ticker_data = ticker_data.sort_values('Date')
    rev_growth_values = ticker_data['Revenue growth'].dropna() * 100

    if len(rev_growth_values) > 0:
        avg_growth = rev_growth_values.mean()
        latest_growth = rev_growth_values.iloc[-1 ] if len(rev_growth_values) > 0 else 0

        print(f"{ticker} average revenue growth : {avg_growth:.1f}%| Current Revenue Growth: {latest_growth:.1f}%")
    else:
        print(f"{ticker} Revenue Growth: No data available")

print('\nR&D trends:\n')
for ticker in sorted(fund_trends['ticker'].unique()):
    ticker_data = fund_trends[fund_trends['ticker'] == ticker].copy()
    ticker_data = ticker_data.sort_values('Date')
    rnd_growth = ticker_data[['Date', 'R&D to Revenue']]
    rnd_growth = ticker_data['R&D to Revenue'] * 100

    if len(rnd_growth) > 0:
        avg_rnd_growth = rnd_growth.mean()
        latest_rnd_growth = rnd_growth.iloc[-1] if len(rnd_growth) > 0 else 0

        print(f"{ticker} Average R&D growth: {avg_rnd_growth:.1f}% | Latest R&D growth: {latest_rnd_growth:.1f}%")
    else: 
        print(f"{ticker} R&D Growth: No data available")

Net Margin:

GOOGL Net Margin Change: 32.8% Current Margin | 11.6% change
META Net Margin Change: 30.1% Current Margin | 10.2% change
MSFT Net Margin Change: 36.1% Current Margin | -0.5% change
NVDA Net Margin Change: 55.6% Current Margin | 39.4% change
PLTR Net Margin Change: 36.3% Current Margin | 55.9% change

Revenue Growth Trends:

GOOGL average revenue growth : 12.5%| Current Revenue Growth: 15.1%
META average revenue growth : 19.9%| Current Revenue Growth: 22.2%
MSFT average revenue growth : 12.5%| Current Revenue Growth: 14.9%
NVDA average revenue growth : 101.8%| Current Revenue Growth: 65.5%
PLTR average revenue growth : 33.9%| Current Revenue Growth: 56.2%

R&D trends:

GOOGL Average R&D growth: 14.5% | Latest R&D growth: 15.2%
META Average R&D growth: 28.5% | Latest R&D growth: 28.5%
MSFT Average R&D growth: 12.2% | Latest R&D growth: 11.5%
NVDA Average R&D growth: 15.0% | Latest R&D growth: 8.6%
PLTR Average R&D growth: 16.8% | Latest R&D growth: 12.5%

<h3>Valuation Snapshot</h3>

a snippet of current stock valuation based on price + fundamentals

In [13]:
latest_fundamentals = fundamentals.sort_values('Date').groupby('ticker').tail(1).reset_index(drop=True)
latest_prices = prices.sort_values('Date').groupby('ticker').tail(1).reset_index(drop=True)

In [14]:
latest_prices

                       Date ticker  close_price     Volume
0 2026-03-09 04:00:00+00:00   NVDA   182.649994  176552775
1 2026-03-09 04:00:00+00:00   MSFT   409.410004   30073894
2 2026-03-09 04:00:00+00:00   PLTR   156.429993   47436735
3 2026-03-09 04:00:00+00:00   META   647.390015   13463314
4 2026-03-09 04:00:00+00:00  GOOGL   306.359985   29263937

In [15]:
latest_prices.shape

(5, 4)

In [16]:
currentvaluation = pd.merge(latest_fundamentals, latest_prices, on='ticker', suffixes=('_fund', '_price'))

print(currentvaluation.columns)

Index(['ticker', 'Date_fund', 'Free Cash Flow', 'Beginning Cash Position',
       'End Cash Position', 'Total Revenue', 'Gross Profit', 'Net Income',
       'Diluted EPS', 'Research And Development', 'EBITDA', 'Tax Provision',
       'Total Debt', 'Working Capital', 'Gross Margin', 'Net Margin',
       'FCF Margin', 'Debt to Equity', 'Working Capital Ratio',
       'R&D to Revenue', 'Revenue growth', 'Net Income Growth', 'EPS Growth',
       'FCF Growth', 'Date_price', 'close_price', 'Volume'],
      dtype='str')

NameError: name 'currentvalution' is not defined